### PR TITLE
Add mysql2 driver

### PR DESCRIPTION
**Pull request by sidorares**

### CODE REVIEW

**Comment by mscdex** [comment]
I'm in the middle of doing a major restructuring for this project, so there will need to be some modifications. The reason for this is to create better organization and have more metrics available like memory usage and CPU usage per benchmark per module.

Stay tuned.

**Comment by sidorares** [comment]
Sure, thanks.
 I'm working currently on node-mysql compatible driver, and on my benchmarks it's considerably faster. Interesting to see independent comparison. Just measuring selects and inserts time is not enough for benchmarks - what are you plans? IMO good test is http server + select + render template benchmark, this way it is most likely used and all components tested: uv thread pool (in case of libmyslclient), GC, and speed of access to db results. 
Benchmarks for mysql2 should be compatible to those of node-mysql, If something is working differently feel free to send bug reports.

**Comment by mscdex** [comment]
Fixed in c205232.

I can see your concern about the particular benchmarks, but IMHO isolating the tests to just queries and such prevents side effects and outside influences that don't involve the driver itself -- which is what we are really benchmarking (i.e. "how fast can I get results from the database?") in a general way.

**Comment by sidorares** [comment]
"how fast can I get results from the database?" is not enough. For example, node-libmysqlclient can give you results sequentially very fast, but if you open more connections than UV pool size, most of them could potentially wait. Its easy to simulate with long queries like 'sleep 0.1': pool + 20 connections would give you 200 rps with non-threadpool based libs and just at most 40 with thead pool size of 4 (it's usually size of number of cores AFAIK)

**Comment by mscdex** [comment]
Isn't that what we're supposed to be benchmarking though, the implementations? There's some that are "plain js", some that use the thread pool, and some that neither. Benchmarking can help to find what kind of implementation works best for node.

**Comment by sidorares** [comment]
The problem is that you don't test thread pool integration with single connection. Maybe there should be benchmark for, say "16 concurrent selects"

**Pull request closed without merging**
